# config/database.yml
default: &default
  host: 'localhost'
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: 'ruby_task'

test:
  <<: *default
  database: 'ruby_task_test'
